version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: checkout karsajobs-ui branch
          command: git clone -b karsajobs-ui https://github.com/NetherP/a433-microservices.git
      - run:
          name: get hadolint
          command: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -O hadolint
      - run:
          name: change permission
          command: chmod +x hadolint
      - run:
          name: run hadolint on dockerfile
          command: ./hadolint a433-microservices/Dockerfile
  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - run:
          name: checkout karsajobs-ui branch
          command: git clone -b karsajobs-ui https://github.com/NetherP/a433-microservices.git
      - run:
          name: build docker image
          working_directory: a433-microservices
          command: docker build -t ghcr.io/netherp/karsajobs-ui:latest .
      - run:
          name: login registry
          command: echo $PASSWORD_GITHUB_PACKAGES | docker login ghcr.io -u NetherP --password-stdin
      - run:
          name: push to ghcr
          command: docker push ghcr.io/netherp/karsajobs-ui:latest
workflows:
  karsajobs-ui-cicd:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
